# Generated by Django 3.2.9 on 2021-11-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=10)),
                ('edept', models.CharField(max_length=10)),
                ('esal', models.FloatField()),
            ],
        ),
    ]
